version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: client/node_modules
          app-dir: client
      - run:
          command: npm run format
          name: Check for Formatting Errors
          working_directory: client
      - run:
          command: npm run lint
          name: Check for Linting Errors
          working_directory: client
      - run:
          command: npm test
          name: Run JavaScript Tests
          working_directory: client
      - run:
          command: npm run build
          name: Build JavaScript
          working_directory: client
      - persist_to_workspace:
          root: ./
          paths:
            - client/prod
            - client/node_modules

  deploy:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ./
      - run: pwd && ls && ls client && ls client/prod
      - run:
          name: Netlify Deploy
          working_directory: client
          command: ./client/node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir client/prod
