version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - save_cache:
          key: v1-myapp-cache
          paths:
            - ~/client
      - node/with-cache:
          steps:
            - run:
                command: npm install
                working_directory: client
                # cd client
                # npm install
                # npm run format
                # npm run lint
                # npm test
                # npm run build

workflows:
  build-and-test:
    jobs:
      - build-and-test
